"""sync_labs_table

Revision ID: 0ba351bd05f0
Revises: 782f2e8edc1b
Create Date: 2026-09-16 17:47:35.831389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ba351bd05f0'
down_revision: Union[str, Sequence[str], None] = '782f2e8edc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false(), comment='是否删除'))
    op.add_column('labs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('labs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.alter_column('labs', 'capacity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='容纳人数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('labs', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='状态：0-关闭，1-开放',
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
    # labs 表原本为手工创建的 MyISAM 引擎，统一为 InnoDB（支持事务）
    op.execute("ALTER TABLE labs ENGINE=InnoDB")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labs', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='状态：0-关闭，1-开放',
               existing_server_default=sa.text("'1'"))
    op.alter_column('labs', 'capacity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='容纳人数',
               existing_server_default=sa.text("'0'"))
    op.drop_column('labs', 'updated_at')
    op.drop_column('labs', 'created_at')
    op.drop_column('labs', 'is_deleted')
    # ### end Alembic commands ###
