"""add_equipment

Revision ID: 4e219eea2b3f
Revises: 0ba351bd05f0
Create Date: 2026-09-17 22:41:07.919754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e219eea2b3f'
down_revision: Union[str, Sequence[str], None] = '0ba351bd05f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='所属实验室'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='设备名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='说明'),
    sa.Column('img', sa.String(length=200), nullable=True, comment='图片'),
    sa.Column('spec', sa.String(length=100), nullable=True, comment='型号规格'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：0-维修，1-正常'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='实验室设备表'
    )
    op.create_index(op.f('ix_equipments_lab_id'), 'equipments', ['lab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipments_lab_id'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
