"""add userindex remove fk

Revision ID: 8f313665b3f6
Revises: 
Create Date: 2026-07-05 09:57:15.759078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f313665b3f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('article', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='昵称',
               existing_nullable=True)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment=None,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'user',
        existing_comment='用户表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='昵称',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='密码',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('article', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('article', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
