"""add_user_id_to_labs

Revision ID: a89dc1181ca4
Revises: efc2a71c6d5b
Create Date: 2026-09-19 17:06:48.616370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89dc1181ca4'
down_revision: Union[str, Sequence[str], None] = 'efc2a71c6d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('user_id', sa.Integer(), nullable=True, comment='创建人'))
    op.create_index(op.f('ix_labs_user_id'), 'labs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labs_user_id'), table_name='labs')
    op.drop_column('labs', 'user_id')
    # ### end Alembic commands ###
