"""add_article_soft_delete

Revision ID: c53d8f9b9272
Revises: 8f313665b3f6
Create Date: 2026-07-05 15:10:29.703999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53d8f9b9272'
down_revision: Union[str, Sequence[str], None] = '8f313665b3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_deleted')
    # ### end Alembic commands ###
