"""add_reservation_model

Revision ID: efc2a71c6d5b
Revises: 13a67b6510f7
Create Date: 2026-09-19 15:42:01.178221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc2a71c6d5b'
down_revision: Union[str, Sequence[str], None] = '13a67b6510f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='预约人'),
    sa.Column('lab_id', sa.Integer(), nullable=False, comment='实验室'),
    sa.Column('equipment_id', sa.Integer(), nullable=True, comment='设备，空表示预约实验室'),
    sa.Column('date', sa.String(length=20), nullable=False, comment='预约日期'),
    sa.Column('start_time', sa.String(length=20), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.String(length=20), nullable=False, comment='结束时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('status', sa.Integer(), nullable=False, comment='预约状态 0 待审核，1 已通过，2 已拒绝，3 已取消'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='预约信息'
    )
    op.create_index(op.f('ix_reservations_equipment_id'), 'reservations', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_reservations_lab_id'), 'reservations', ['lab_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_lab_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_equipment_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
