"""add_user_soft_delete

Revision ID: f8d632f9ce2d
Revises: c53d8f9b9272
Create Date: 2026-07-08 22:56:02.816071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d632f9ce2d'
down_revision: Union[str, Sequence[str], None] = 'c53d8f9b9272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('fk_article_user'), table_name='article')
    op.create_index(op.f('ix_article_user_id'), 'article', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_index(op.f('ix_article_user_id'), table_name='article')
    op.create_index(op.f('fk_article_user'), 'article', ['user_id'], unique=False)
    # ### end Alembic commands ###
